# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeff Rogers
title: Experienced Technology Delivery Leader - Chicago, IL
email: jeff@atriumn.com
phone: 312.282.9879

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: jrojers

# Additional icon links
additional_links:
    - title: Jeff Rogers
      icon: fas fa-globe
      url: https://jeff-atriumn.github.io/
    - title: Calendly
      icon: far fa-calendar-plus
      url: https://calendly.com/jeff-atriumn

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/cartoonify.png
about_content: | # this will include new lines to allow paragraphs
    An experienced leader in agile software delivery, with successes in <mark>continuous delivery</mark> and <mark>proactive risk management</mark>, while advocating <mark>quality as a design principle</mark>.

    Deep focus on aligning <mark>key performance indicators</mark> as a tool for continuous improvement in technology strategy and product roadmaps.

    Broad practical delivery experience across many business verticals: healthcare, regulatory, ecommerce, insurance, and more.

    - risk management

    - product management, design, & requirements

    - architecture & system design

    - verification & validation

    - release, observability, and continuous improvement


    Schedule time [here](https://calendly.com/jeff-atriumn).

content:
    - title: Experience
      layout: list
      content:
          - layout: left
            title: Tempus Labs
            link: https://tempus.com
            sub_title: Head of Engineering Quality / Engineering Practices Lead
            caption: September 2017 - July 2021
            quote: >
                Tempus makes precision medicine a reality through the power and promise of data and artificial intelligence.
            description: | # this will include new lines to allow paragraphs
                Enabled continuous delivery of independent and autonomous pods via <mark>proactive risk identification, observation, and mitigation processes</mark>.

                Build procedures for proactive verification and validation, continuous delivery, and incident/root-cause analysis processes, with a "shift-left" philosophy in defining <mark> quality as a design principle</mark>.

                Coached 20+ teams on weekly, monthly, and quarterly <mark>continuous improvement and risk evaluation</mark> via failure mode analysis, retrospectives, and quarterly planning.

                Authored official Tempus SDLC describing <mark>system and infrastructure change management policies and procedures</mark>. Acted as liaison between Technology teams and Tempus Legal and Compliance groups, contributing to 50+ regulatory or partner audits.

                Facilitated the adoption of delivery and quality KPIs via <mark>internal workflow, dependency, and release management tooling</mark>.

                Rebooted internal procedures on incident response, root-cause analysis, continuous improvement, while sharing learnings & failures.

                - Accountable to internal product release and dependency management tooling for 500+ systems and services.

                - Contributed to 20+ internal policies detailing procedures around change & risk management, data security, and validation.

                - Coached 20+ cross-functional Product & Engineering teams on testing, deployment planning, and continuous integration with hourly/daily/weekly releases.

                - Designed and delivered Technology onboarding procedures and training.

                - Collaborated weekly with internal Architecture guild on platform direction.

                - Grew Engineering Operations release & testing expertise from O to 15 people.

          - layout: left
            title: Centro
            link: https://www.centro.net
            sub_title: Senior Director of Quality Engineering
            caption: September 2014 - September 2017
            quote: >
                A global provider of enterprise-class software for digital advertisers. Its ad-tech SAAS platform is the industry’s most powerful, comprehensive, and automated digital media management platform.

            description: | # this will include new lines to allow paragraphs
                Owned Product & Engineering delivery procedures and practices for Centro's SAAS platform, [Basis](https://platform.basis.net).

                <mark>Positioned Quality Engineering as a facilitator of high quality delivery</mark>, via interaction with individual contributors, team leads, senior management, and customer liaisons.

                Coached teams on <mark>quality and delivery related KPIs for individuals, teams, and the organization</mark>. Facilitated KPI communications with executive team on quality of code, team velocities, releases, and production operations.

                - Interfaced with executive leaders and business owners as the owner of Technology quality and change management.

                - Owned development, quality, and release processes across three technology offices, with over 100 engineers, project managers, designers, and test engineers. Directly managed 10+ SDET and Test Engineers.

                - Responsible for change management processes and documentation for all web and backend updates to production.

                - Mentored engineering teams on test automation practices across frontend, backend, end-to-end, performance, load, and data quality.

                - Shaped recruiting, onboarding, and staffing for Quality Assurance/Test Engineering positions, as well as engineer, product, and operations positions.

          - layout: left
            title: Angie's List / Angi
            link: https://www.angi.com/
            sub_title: Director of Engineering QA
            caption: January 2013 - September 2014
            quote: >
                An American home services online directory that allows users to read and publish crowd-sourced reviews of local businesses and contractors.

            description: | # this will include new lines to allow paragraphs
                Responsible for software quality and releases of the Angie’s List platforms, which included mobile, web, and external/internal APIs.

                Mentored engineering teams on <mark>frontend, backend, end-to-end, and performance test automation strategies</mark>.

                - Built quality processes for two major Engineering offices, with over 125 engineers.

                - Shaped performance testing and improvement plans to support over 2 million members and service providers.

                - Condensed all feature/project planning and knowledge management from 10 disparate tools into one common platform for all of Angie’s List.

                - Oversaw Angie’s List scrum masters and Scrum process implementation across 10+ Product & Engineering teams.

                - Assisted architecture group with the strategy to redesign a highly monolithic, 10 year old codebase.

                - Owned recruiting, onboarding, and staffing for Test Engineering and Scrum Master positions.

          - layout: left
            title: Groupon
            link: https://www.groupon.com
            sub_title: Senior Engineering Manager
            caption: October 2010 - January 2013
            quote: >
                A global e-commerce marketplace connecting subscribers with local merchants by offering activities, travel, goods and services via crowdsourced discounts.

            description: | # this will include new lines to allow paragraphs
                Responsible for overall product quality strategy, through <mark>investment in test driven development</mark> at several layers of the Groupon platform. This investment enabled the Product & Engineering teams to build systems quickly and efficiently, without compromising quality standards.

                Championed the adoption of <mark>delivery and quality KPIs</mark> for decision support: tracking CI build performance, test stability, code coverage analysis, and much more.

                Collaborated with global Engineering leaders on a <mark>holistic service-oriented architecture testing strategy</mark> - with a focus on end-to-end, full stack integration testing, and "last mile" delivery across multiple platforms and locales (web, mobile, APIs).

                - Owned test and productivity processes for an agile development environment distributed across two major US development centers, with over 300 engineers.

                - Coached 20+ cross-functional Product & Engineering teams on testing, deployment planning, and continuous integration with hourly/daily/weekly releases.

                - Responsible for recruiting, onboarding, and staffing for Quality Engineering positions for the Chicago development center. Grew team from 1 to 15 in less than 2 years.

                - Managed back-end quality processes for Financial Engineering groups, which saw $2+ million flow to merchants daily.

                - Facilitated processes and tools to enable internal “dogfooding” of software releases to all Groupon employees.

                - Designed an apprenticeship program for junior/mid-level developers to learn testing practices on the job, before graduating to full-time Engineering or Quality positions.

          - layout: left
            title: ThoughtWorks
            link: https://www.thoughtworks.com
            sub_title: Lead Consultant
            caption: July 2000 - October 2010
            quote: >
                A leading global technology consultancy in Agile software development. Integrating strategy, design, and software engineering to enable enterprises and technology across the globe to thrive.

            description: | # this will include new lines to allow paragraphs
                Lead the charge of building the testing and quality assurance capabilities and practices in the ThoughtWorks agile practice. Primary responsibilities focused on client project execution: <mark>Delivery assurance, project management, and coaching</mark>.

                Accountable to product test strategies, plans, and staffing to proactively mitigate risk and address quality gaps. Close collaboration with ThoughtWorks and client partner leaders on leveraging staff, budgets, and tools for robust test automation strategies.

                - Built a team of 30+ testing professionals that were staffed on projects of varying sizes and technologies across North America, the United Kingdom, and Australia.

                - Coached embedded teams on agile testing principles and practices at over 25 ThoughtWorks clients.

                - Collaborated on approvals for North American client engagements with ThoughtWorks Legal and Staffing departments, ensuring project coverage for cross-functional quality and testing concerns.

                - United international ThoughtWorks testing leaders on strategic goals, such as bars for recruiting, partnerships, and agile testing visions.

    - title: Education # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: Miami University, Oxford OH
            link: https://miamioh.edu/
            caption: Management Information Systems and Analytics
            sub_title: Bachelors of Science in Business
            sub_title: 1994 - 1998
            quote: >
                Miami University, founded in 1809 in Oxford, Ohio, has a national reputation for a superior educational experience and unparalleled professional preparation of its students.
            description: | # this will include new lines to allow paragraphs
                - The management information systems (MIS) major provides managerial and technical skills critical to directing and controlling the information resources of an organization.

                - Graduates of this program learn fundamental information and communication theories and technologies such as database theory and management, systems analysis/design, and data communications as well as contemporary topics such as internetworking and world wide web-based technologies for electronic commerce, data and wireless communications, multimedia, data mining and warehousing, knowledge management, and enterprise systems.

                - Emphasis is on structuring and solving business problems by appropriately applying technological resources and information management skills.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
