# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeff Rogers
title: Executive Technology Delivery Leader - Chicago, IL
email: jeff@atriumn.com
phone: 312.282.9879
website: https://jeff-atriumn.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: jrojers

# Additional icon links
additional_links:
    - title: Jeff Rogers
      icon: fas fa-globe
      url: https://jeff-atriumn.github.io/
    - title: Calendly
      icon: far fa-calendar-plus
      url: https://calendly.com/jeff-atriumn

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/cartoonify.png
about_content: | # this will include new lines to allow paragraphs
    A senior software engineering leader, with a focus on <mark>Continuous Delivery</mark> and <mark>Risk Management</mark>.

    practices

    <mark>quality as a design principle</mark>

    cicd

    quality system

    agile - scrum

    continuous improvement

    risk observation, identification, management/mitigation, escalation

    robust - scalable arch & process

    schedule time [here](https://calendly.com/jeff-atriumn)


content:
    - title: Experience
      layout: list
      content:
          - layout: left
            title: Tempus Labs
            link: https://tempus.com
            sub_title: Head of Engineering Quality / Engineering Lead
            caption: September 2017 - July 2021
            quote: >
                Tempus is making precision medicine a reality through the power and promise of data and artificial intelligence.

With the world’s largest library of clinical and molecular data, and an operating system to make that data accessible and useful, we enable physicians to make real-time, data-driven decisions to deliver personalized patient care, and in parallel, facilitate discovery, development, and delivery of optimized therapeutic options for patients through distinctive solution sets.
            description: | # this will include new lines to allow paragraphs
                - SDLC

                - engineering operations

                - quality as a design principle

                - KPIs

                - Depcom

                - O to 15 hires

                - Regulations, ISO certification, audits, business

                - liaison between Technology, Legal, Compliance

                - major incidents, rca, continuous improvement

                - onboarding

                - agile training

                - independent / autonomous

          - layout: left
            title: Centro
            link: https://www.centro.net
            sub_title: Senior Director of Quality Engineering
            caption: September 2014 - September 2017
            quote: >
                Own engineering quality for Centro's ad-tech SAAS platform (https://platform.basis.net).
            description: | # this will include new lines to allow paragraphs
                - Interface with executive leaders and business owners the owner of Technology quality and change management.

                - Own development, quality, and release processes for three technology offices, with over 100 engineers, project managers, designers, and testers.

                - Directly manage 10+ SDET and exploratory testing professionals.

                - Responsible for change management for all web and backend updates to production.

                - Mentor engineering teams on test automation across frontend, backend, end-to-end,  performance,  load, and data quality.

                - Shape recruiting, onboarding, and staffing for Quality Assurance/Test Engineering positions, as well as engineer, product, and operations positions.

          - layout: left
            title: Angie's List / Angi
            link: https://www.angi.com/
            sub_title: Director of Engineering QA
            caption: January 2013 - September 2014
            quote: >
                Responsible for software quality and releases of the Angie’s List platforms, which include mobile, web, and public and internal APIs.
            description: | # this will include new lines to allow paragraphs
                - Represent Engineering as the owner of quality, with individual engineering contributors to senior management to customers.

                - Build quality processes for two major engineering offices, with over 125 engineers.

                - Shape performance testing and improvement plans to support over 2 million members and service providers.

                - Set quality metrics for individuals, teams, and organizations.

                - Handle processes and reporting for all web, mobile, and backend releases to production.

                - Mentor engineering teams on frontend, backend, end-to-end, and performance test automation strategies.

                - Condense all feature/project planning and knowledge management from 10 disparate tools into one common platform for all of Angie’s List (Jira and Confluence).

                - Oversee Angie’s List scrum masters and Scrum process implementation.

                - Continuous interaction with peers in Engineering, Sales, Marketing, Operations, and Customer Call Centers.

                - Handle communications with executive team on quality of code, team velocities, releases, and production operations.

                - Assist architecture group with the strategy to redesign a highly monolithic, 10 year old codebase.

                - Design quality engineering process that drive the creation of high quality code.

                - Own all release processes and metrics, which involves heavy interaction with accounting and financial controls.

                - Shape recruiting, onboarding, and staffing for Quality Assurance/Test Engineering positions, as well as developer, release, and Scrum Master positions.

          - layout: left
            title: Groupon
            link: https://www.groupon.com
            sub_title: Senior Engineering Manager
            caption: October 2010 - January 2013
            quote: >
                Responsible for overall software quality strategy, through investment in test driven development at several layers of the Groupon platform. This investment enables the engineering team to build products quickly and efficiently, without compromising our quality standards.
            description: | # this will include new lines to allow paragraphs
                - Built test and productivity processes for a fast and agile environment distributed across two major US development centers, with over 300 engineers.

                - Accountable for acceptance and regression testing with the hourly/daily/weekly deployments of 20+ engineering teams.

                - Built scripts and tools to track and report quality metrics. Examples: CI build performance, test stability, code coverage, and test coverage analysis.

                - Mentored test engineering teams on frontend, backend, and end-to-end test automation strategies.

                - Collaborated closely with Release Engineering on deployment planning and continuous integration infrastructure. CI builds run ~30,000 tests on every commit.

                - Responsible for recruiting, onboarding, and staffing for Quality Assurance/Test Engineering positions for the Chicago development center. The team grew from 1 to 15 in less than 2 years.

                - Steady interaction with peers in Engineering & Product Management regarding holes in quality, process, or both.

                - Championed international service-oriented architecture functional testing strategy, represent end-to-end, full stack testing in global architecture discussions.

                - Owned long-term end-to-end testing across multiple platforms (web, api, mobile) and locales.

                - Managed back-end quality processes for Financial Engineering groups, which sees $2+ million flow to merchants daily.

                - Facilitated processes and tools to enable internal “dogfooding” of software releases to all Groupon employees.

                - Designed an apprenticeship program for junior/mid-level developers to learn good testing practices “on the job”, before graduating to development positions.

          - layout: left
            title: ThoughtWorks
            link: https://www.thoughtworks.com
            sub_title: Lead Consultant
            caption: July 2000 - October 2010
            quote: >
                Charged with building the testing and quality assurance capabilities and practices of a global consulting and professional services organization, with a focus on Agile optimization.
            description: | # this will include new lines to allow paragraphs
                - Responsibilities included business development, recruiting, coaching, project management, delivery assurance, as well as project execution.

                - Built a team of 30+ enthusiastic testers that could be staffed on projects of varying sizes and technologies across North America, the United Kingdom, and Australia.

                - Helped clients build test strategies, plans, and teams to address their quality concerns, with an eye towards "shift-left" agile design principles.

                - This includes resource planning and management, to ensure that all testing and quality system facets of the project are covered.

                - Approved North American client engagements for legal, staffing, and project coverage, focusing on cross-functional quality and testing management.

                - Coached client QA professionals on agile testing principles and practices at over 25 ThoughtWorks clients.

                - Worked closely with Engineering leaders on leveraging staff and tools for robust test automation strategies. Represented open source testing tools or “roll your own” strategies over commercial, more expensive options.

                - Collaborated with international testing leaders on strategic goals, such as bars for recruiting, partnerships, and agile testing visions.

    - title: Education # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: Miami University, Oxford OH
            link: https://miamioh.edu/
            caption: 1994 - 1998
            sub_title: Bachelors of Science in Business - Management Information Systems / Information Systems and Analytics
            quote: >
                Miami University, founded in 1809 in Oxford, Ohio, has a national reputation for a superior educational experience and unparalleled professional preparation of its students.
            description: | # this will include new lines to allow paragraphs
                - The management information systems (MIS) major provides managerial and technical skills critical to directing and controlling the information resources of an organization.

                - Graduates of this program learn fundamental information and communication theories and technologies such as database theory and management, systems analysis/design, and data communications as well as contemporary topics such as internetworking and world wide web-based technologies for electronic commerce, data and wireless communications, multimedia, data mining and warehousing, knowledge management, and enterprise systems.

                - Emphasis is on structuring and solving business problems by appropriately applying technological resources and information management skills.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
